package nominas.gui;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import nominas.control.UserController;
import nominas.entity.User;

public class LoginFrame extends javax.swing.JFrame {

    // Variable que indica si el usuario esta logueado en el sistema
    public boolean isGuess = true;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        Image img = Toolkit.getDefaultToolkit().getImage("res/icon.png");
        initComponents();
        this.setIconImage(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        statusBar = new javax.swing.JLabel();

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Nominas");

        txtUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nominas/ico/unlock_.png"))); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        lblUser.setText("Usuario:");

        lblPass.setText("Contraseña:");

        txtPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        statusBar.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        statusBar.setForeground(new java.awt.Color(102, 102, 102));
        statusBar.setText("Ingresa tus datos para comenzar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusBar, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUser)
                            .addComponent(lblPass)
                            .addComponent(txtUser)
                            .addComponent(txtPass)
                            .addComponent(btnEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(statusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setIncorrect(JLabel label) {
        label.setForeground(Color.RED);
        statusBar.setText("Corrige el campo marcado y vuelve a intentar");
        statusBar.setForeground(Color.RED);
    }
    
    private void reInitColors(){
        lblUser.setForeground(Color.BLACK);
        lblPass.setForeground(Color.BLACK);
        statusBar.setForeground(Color.GRAY);
    }

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        reInitColors();
        statusBar.setText("Validando...");
        //Se genera un objeto con los datos ingresados
        String username = txtUser.getText();
        String password = new String(txtPass.getPassword());

        //Se evaluan los campos
        if (username.trim().length() < 4)
            setIncorrect(lblUser);        
        else if(password.trim().length() < 4) 
            setIncorrect(lblPass);        
        else {
            //Se comprueba si es un usuario valido
            try {
                //Usuario, Contraseña, Tipo de Usuario (0)
                User user = new User(username, password, 0);
            //El tipo de usuario se configura automaticamente

                boolean valid = new UserController().isValidUser(user);
                if (valid) {
                    isGuess = false;
                    statusBar.setText("Ingresando...");
                } else {
                    isGuess = true;
                    statusBar.setText("Tus datos son incorrectos, intenta de nuevo");
                }

            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel statusBar;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
